color0 #191206
color1 #ffb4ab
color2 #ffb4a3
color3 #ffb4a3
color4 #edc06c
color5 #ffb4a3
color6 #ffb4a3
color7 #f0e0ca
color8 #a28e6e
color9 #ffb4ab
color10 #ffb4a3
color11 #ffb4a3
color12 #edc06c
color13 #ffb4a3
color14 #ffb4a3
color15 #f0e0ca

cursor                #f0e0ca
cursor_text_color     #191206
background            #191206
foreground            #f0e0ca
selection_foreground  #dac4a0
selection_background  #54452a
active_border_color   #ffb4a3
inactive_border_color #54452a
url_color             #ffb4a3

active_tab_foreground   #5e1605
active_tab_background   #ffb4a3
inactive_tab_foreground #dac4a0
inactive_tab_background #54452a
cursor_trail_color      #dac4a0
