color0 #0f150b
color1 #ffb4ab
color2 #f3bf48
color3 #e9c16c
color4 #add28e
color5 #f3bf48
color6 #e9c16c
color7 #dfe5d3
color8 #88957b
color9 #ffb4ab
color10 #f3bf48
color11 #e9c16c
color12 #add28e
color13 #f3bf48
color14 #e9c16c
color15 #dfe5d3

cursor                #dfe5d3
cursor_text_color     #0f150b
background            #0f150b
foreground            #dfe5d3
selection_foreground  #becbae
selection_background  #3f4a34
active_border_color   #f3bf48
inactive_border_color #3f4a34
url_color             #f3bf48

active_tab_foreground   #402d00
active_tab_background   #f3bf48
inactive_tab_foreground #becbae
inactive_tab_background #3f4a34
cursor_trail_color      #becbae
