color0 #131407
color1 #ffb4ab
color2 #ffb86f
color3 #fcb975
color4 #c7cc79
color5 #ffb86f
color6 #fcb975
color7 #e5e4cd
color8 #929373
color9 #ffb4ab
color10 #ffb86f
color11 #fcb975
color12 #c7cc79
color13 #ffb86f
color14 #fcb975
color15 #e5e4cd

cursor                #e5e4cd
cursor_text_color     #131407
background            #131407
foreground            #e5e4cd
selection_foreground  #c8c9a6
selection_background  #47482e
active_border_color   #ffb86f
inactive_border_color #47482e
url_color             #ffb86f

active_tab_foreground   #4a2800
active_tab_background   #ffb86f
inactive_tab_foreground #c8c9a6
inactive_tab_background #47482e
cursor_trail_color      #c8c9a6
