hl.on("hyprland.start", function()
	hl.exec_cmd("udiskie")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprpolkit")
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("$HOME/.config/hypr/scripts/resetxdgportal.sh")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("wl-clip-persist --clipboard regular")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE")
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
end)
