
$image = wallpapers/glass-gray.png
$background = rgba(0f1512ff)

$image = wallpapers/glass-gray.png
$error = rgba(ffb4abff)

$image = wallpapers/glass-gray.png
$error_container = rgba(93000aff)

$image = wallpapers/glass-gray.png
$inverse_on_surface = rgba(2c322eff)

$image = wallpapers/glass-gray.png
$inverse_primary = rgba(1a6b51ff)

$image = wallpapers/glass-gray.png
$inverse_surface = rgba(dee4dfff)

$image = wallpapers/glass-gray.png
$on_background = rgba(dee4dfff)

$image = wallpapers/glass-gray.png
$on_error = rgba(690005ff)

$image = wallpapers/glass-gray.png
$on_error_container = rgba(ffdad6ff)

$image = wallpapers/glass-gray.png
$on_primary = rgba(003828ff)

$image = wallpapers/glass-gray.png
$on_primary_container = rgba(a6f2d2ff)

$image = wallpapers/glass-gray.png
$on_primary_fixed = rgba(002116ff)

$image = wallpapers/glass-gray.png
$on_primary_fixed_variant = rgba(00513bff)

$image = wallpapers/glass-gray.png
$on_secondary = rgba(1e352cff)

$image = wallpapers/glass-gray.png
$on_secondary_container = rgba(cee9dbff)

$image = wallpapers/glass-gray.png
$on_secondary_fixed = rgba(092017ff)

$image = wallpapers/glass-gray.png
$on_secondary_fixed_variant = rgba(354b41ff)

$image = wallpapers/glass-gray.png
$on_surface = rgba(dee4dfff)

$image = wallpapers/glass-gray.png
$on_surface_variant = rgba(bfc9c2ff)

$image = wallpapers/glass-gray.png
$on_tertiary = rgba(0a3545ff)

$image = wallpapers/glass-gray.png
$on_tertiary_container = rgba(c2e8fdff)

$image = wallpapers/glass-gray.png
$on_tertiary_fixed = rgba(001f2aff)

$image = wallpapers/glass-gray.png
$on_tertiary_fixed_variant = rgba(264b5cff)

$image = wallpapers/glass-gray.png
$outline = rgba(89938dff)

$image = wallpapers/glass-gray.png
$outline_variant = rgba(404944ff)

$image = wallpapers/glass-gray.png
$primary = rgba(8ad6b6ff)

$image = wallpapers/glass-gray.png
$primary_container = rgba(00513bff)

$image = wallpapers/glass-gray.png
$primary_fixed = rgba(a6f2d2ff)

$image = wallpapers/glass-gray.png
$primary_fixed_dim = rgba(8ad6b6ff)

$image = wallpapers/glass-gray.png
$scrim = rgba(000000ff)

$image = wallpapers/glass-gray.png
$secondary = rgba(b3ccbfff)

$image = wallpapers/glass-gray.png
$secondary_container = rgba(354b41ff)

$image = wallpapers/glass-gray.png
$secondary_fixed = rgba(cee9dbff)

$image = wallpapers/glass-gray.png
$secondary_fixed_dim = rgba(b3ccbfff)

$image = wallpapers/glass-gray.png
$shadow = rgba(000000ff)

$image = wallpapers/glass-gray.png
$source_color = rgba(9fa6a1ff)

$image = wallpapers/glass-gray.png
$surface = rgba(0f1512ff)

$image = wallpapers/glass-gray.png
$surface_bright = rgba(343b37ff)

$image = wallpapers/glass-gray.png
$surface_container = rgba(1b211eff)

$image = wallpapers/glass-gray.png
$surface_container_high = rgba(252b28ff)

$image = wallpapers/glass-gray.png
$surface_container_highest = rgba(303633ff)

$image = wallpapers/glass-gray.png
$surface_container_low = rgba(171d1aff)

$image = wallpapers/glass-gray.png
$surface_container_lowest = rgba(0a0f0dff)

$image = wallpapers/glass-gray.png
$surface_dim = rgba(0f1512ff)

$image = wallpapers/glass-gray.png
$surface_tint = rgba(8ad6b6ff)

$image = wallpapers/glass-gray.png
$surface_variant = rgba(404944ff)

$image = wallpapers/glass-gray.png
$tertiary = rgba(a6cce0ff)

$image = wallpapers/glass-gray.png
$tertiary_container = rgba(264b5cff)

$image = wallpapers/glass-gray.png
$tertiary_fixed = rgba(c2e8fdff)

$image = wallpapers/glass-gray.png
$tertiary_fixed_dim = rgba(a6cce0ff)

