"$schema" = 'https://starship.rs/config-schema.json'
palette = "noctalia"
add_newline = false

format = """$directory$line_break$character"""
right_format = """$git_branch$git_status$git_state"""
command_timeout = 200

[package]
disabled = true

[character]
success_symbol = "[❯](purple)"
error_symbol = "[!](red)"
vimcmd_symbol = "[❮](green)"

[directory]
truncation_length = 5

[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = " "
"Pictures" = "  "

[golang]
symbol = " "
format = "[$symbol($version)](bold cyan)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = ' '

[git_status]
conflicted = "*"
untracked = "*"
modified = "*"
staged = "s"
renamed = "r"
deleted = "d"
stashed = "≡"

[nodejs]
disabled = true
format = "[$symbol$version]($style)"
detect_files = ["package.json"]

[python]
pyenv_prefix = "pyenv "
symbol = "🐍 "
disabled = false
detect_extensions = ["py", "ipynb"]






# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette (wallpaper-based)
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#ffb4a3"
red       = "#ffb4ab"
green     = "#ffb4a3"
yellow    = "#edc06c"
cyan      = "#ffb4a3"
magenta   = "#ffb4a3"
white     = "#f0e0ca"
black     = "#191206"

# Extended palette (Catppuccin-compatible names)
rosewater = "#edc06c"
flamingo  = "#edc06c"
pink      = "#ffb4a3"
mauve     = "#9c432e"
maroon    = "#ffb4ab"
peach     = "#edc06c"
teal      = "#ffb4a3"
sky       = "#ffb4a3"
sapphire  = "#ffb4a3"
lavender  = "#9c432e"

# Text shades
text      = "#f0e0ca"
subtext1  = "#dac4a0"
subtext0  = "#a28e6e"

# Surface shades
overlay2  = "#a28e6e"
overlay1  = "#dac4a0"
overlay0  = "#54452a"
surface2  = "#54452a"
surface1  = "#191206"
surface0  = "#191206"
base      = "#191206"
mantle    = "#191206"
crust     = "#412d00"
# <<< NOCTALIA STARSHIP PALETTE <<<
